name: CI Pipeline

on:
    pull_request:
    push:
        branches:
            - main

permissions:
    contents: write
    id-token: write

concurrency:
    group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
    cancel-in-progress: true

jobs:
    lint-test-js:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              if: github.event_name == 'pull_request'
              uses: actions/checkout@v4
              with:
                ref: ${{ github.event.pull_request.head.ref }}

            - name: Checkout
              if: github.event_name == 'push'
              uses: actions/checkout@v4
              
            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                node-version: '21.6.2'
                cache: 'npm' # caching npm dependencies

            - name: Install dependencies
              run: npm install

            - name: Run formatter
              run: npm run ci:format

            - name: Run linter
              run: npm run ci:lint

            - name: Install production dependencies
              run: npm ci -- production
            
            - name: Rebuild the dist directory
              run: npm run ci:build

            - name: Run tests
              run: npm run ci:test
            
            - name: Commit any differences after linting
              if: github.event_name == 'pull_request'
              run: |
                if [ "$(git status | grep -i 'modified\|untracked' | wc -l)" -gt "0" ]; then
                    echo "Detected some changes after linting, committing them now..."
                    git add .
                    git config --local user.email "github-actions[bot]@users.noreply.github.com"
                    git config --local user.name "github-actions[bot]"
                    git commit -m "Linting changes"
                    git push
                fi